# 커스텀 에러와 에러 확장

개발을 하다 보면 자체 에러 클래스가 필요한 경우가 종종 생긴다. 네트워크 관련 작업 중 에러가 발생했다면 `HttpError`, 데이터베이스 관련 작업 중 에러가 발생했다면 `DbError`, 검색 관련 작업 중 에러가 발생했다면 `NotFoundError`를 사용하는 것이 직관적이기 때문이다.

자바스크립트는 여기서 더 나아가 직접 에러를 정의할 수 있다. 그렇다면 발생한 에러에 대해 어떤 에러인지 식별하기 쉬워진다.

그렇다면 커스텀 에러를 만드는 가장 간단한 방법은 에러의 프로토타입을 확장하고 생성자를 통해 원래 에러를 초기화하는 것이다. 나는 이 과정을 클래스와 상속을 통해 구현해보려고 한다.

### 에러 정의하기

에러를 정의하려면 에러를 상속받아야 하는데 그 전에 에러 객체의 기본적인 구조를 알아야 한다.

```jsx
class Error {
  constructor(message) {
    this.message = message; // 에러 메시지
    this.name = "Error"; // 에러로 표시될 이름
    this.stack = [call stack]; // stack은 표준은 아니지만, 대다수 환경이 지원함
  }
}
```

- `message`: 에러 객체안에 들어있는 에러 메시지를 갖는 프로퍼티
- `name`: 에러가 발생할 때 `ReferenceError`와 같이 에러의 이름을 표시해 주는 프로퍼티
- `stack`: 에러 전에 있는 `call stack`들을 갖는 프로퍼티

그렇다면 이제 직접 에러를 생성해보자!

```jsx
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
  }
}

throw new ValidationError('에러 발생!');
```

`Error`객체 역시 `Array`처럼 클래스로 상속받을 수 있다. 나는 값 검증 실패 에러를 만들기 위해 에러 이름을 `ValidationError`로 지정한 에러 클래스 `ValidationError`를 선언했다.  

커스텀 에러 클래스를 작성할 땐 반드시 자식 생성자 안에서 `super`를 호출해 줘야 한다. 부모 생성자에서 `message`프로퍼티가 설정되기 때문이다. 부모 생성자에서는 `message`프로퍼티 뿐만 아니라 `name`프로퍼티도 기본값으로 설정되기 때문에 자식 생성자에서 원하는 이름으로 재설정 해줘도 된다.

그리고 `throw`문법으로 새로 만든 에러를 던져봤다.

```bash
throw new ValidationError('에러 발생!');
^

ValidationError: 에러 발생! # 에러 네임과 메시지
    at Object.<anonymous> (/home/chanyeong/dev/test/test/js.js:8:7) # call stack
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

다음과 같은 에러 출력을 얻을 수 있었다. 가장 위에는 에러가 발생한 지점, 그리고 그 아래에 `name`프로퍼티로 설정한 에러의 이름과 객체를 생성할 때 넣어준 `message`값, 에러가 발생하기 까지의 `call stack`이 출력되는 것을 알 수 있다.

### 더 깊게 상속하기

방금 구현한 `ValidationError`클래스를 한번 더 상속해 새로운 에러를 만들 수 도 있다. 그렇다면 이번에는 데이터를 포함한 구체적인 에러 클래스를 생성해보자!

```jsx
class ValidationError extends Error {
  constructor(message) {
    super(message);
    this.name = 'ValidationError';
  }
}

class PropertyRequiredError extends ValidationError {
  constructor(property) {
    super(`No property: ${property}`);
    this.name = 'PropertyRequiredError';
    this.property = property;
  }
}

throw new PropertyRequiredError('age');
```

다음과 같이 `ValidationError`를 상속받은 `PropertyRequiredError`클래스를 작성했다. `PropertyRequiredError`클래스는 객체에 특정 프로퍼티가 없을 때 발생시키는 에러이다. 이전 에러 클래스와 다른 점은 `property`가 추가되었다는 점이다.

그리고 `throw`문법으로 다시 한번 에러를 던져봤다.

```bash
throw new PropertyRequiredError('age');
^

PropertyRequiredError: No property: age
    at Object.<anonymous> (/home/chanyeong/dev/test/test/js.js:17:7)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  property: 'age'
}
```

에러 출력을 확인해보니 이전과는 달리 `property`라는 값이 출력되는 것을 알 수 있다. 이런 식으로 커스텀 에러를 작성 하면 에러 출력을 보고 어떤 에러이고, 어떤 프로퍼티에서 문제가 생겼는지 빠르게 파악할 수 있다.